apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: kunde-vertrag-subscription
spec:
  topic: kunden-vertrag-topic
  routes:
    default: /vertrag/kunde/sync
  pubsubname: redis-pub-sub
scopes:
  - vertrag-service
