apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: mitarbeiter-vertrag-subscription
spec:
  topic: mitarbeiter-vertrag-topic
  routes:
    default: /vertrag/mitarbeiter/sync
  pubsubname: redis-pub-sub
scopes:
  - vertrag-service
