apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: monatsabschluss-rollback
spec:
  topic: monatsabschluss-topic-rollback
  routes:
    default: /monatsabschluss/rollback
  pubsubname: redis-pub-sub
scopes:
  - zeiterfassung-service
