apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: projekt-subscription
spec:
  topic: projekt-topic
  routes:
    default: /vertrag/projekt/sync
  pubsubname: redis-pub-sub
scopes:
  - vertrag-service
